name: "electric_quickstart"

services:
  postgres:
    image: docker.io/postgres:16-alpine
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54321:5432"
    volumes:          
      - pgdata:/var/lib/postgresql/data
    # tmpfs:
    #   - /var/lib/postgresql/data
    #   - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  electric:
    image: docker.io/electricsql/electric:latest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      # Not suitable for production https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
      ELECTRIC_STORAGE_DIR: /var/lib/electric/persistent
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:                         
  pgdata: