'use client'
import { ReactElement, ReactNode } from 'react';
import type { Metadata } from "next";
import { Shell } from '@repo/design-system/components/shell';
import { Box } from '@repo/design-system/components/box';
import { Separator } from '@repo/design-system/components/ui/separator';
import { cn } from "@repo/design-system/lib/utils"
// import "@repo/design-system/globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Docs",
//   description: "Generated by create turbo",
// };

interface RootLayoutProps {
  children: ReactNode // | ReactElement | JSX.Element
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  // export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>  {/* <body className={inter.className}> */}
        <Shell title="Docs">
          <Box>ABC</Box>
          <Separator />
          {children}
        </Shell>
      </body>
    </html>
  )
}

export default RootLayout;